### ISSUE TITLE
SystemError: initialization of _internal failed without raising an exception

### ISSUE THREAD

**Issue by bfgball** [facebookresearch/audiocraft#143]
```
Loading model melody
Traceback (most recent call last):
  File "C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\AI\audiocraft\app.py", line 159, in predict_full
    load_model(model)
  File "D:\AI\audiocraft\app.py", line 92, in load_model
    MODEL = MusicGen.get_pretrained(version)
  File "D:\AI\audiocraft\audiocraft\models\musicgen.py", line 100, in get_pretrained
    lm = load_lm_model(name, device=device, cache_dir=cache_dir)
  File "D:\AI\audiocraft\audiocraft\models\loaders.py", line 90, in load_lm_model
    model = builders.get_lm_model(cfg)
  File "D:\AI\audiocraft\audiocraft\models\builders.py", line 99, in get_lm_model
    condition_provider = get_conditioner_provider(kwargs["dim"], cfg).to(cfg.device)
  File "D:\AI\audiocraft\audiocraft\models\builders.py", line 143, in get_conditioner_provider
    conditioners[str(cond)] = ChromaStemConditioner(
  File "D:\AI\audiocraft\audiocraft\modules\conditioners.py", line 499, in __init__
    self.chroma = ChromaExtractor(sample_rate=sample_rate, n_chroma=n_chroma, radix2_exp=radix2_exp,
  File "D:\AI\audiocraft\audiocraft\modules\conditioners.py", line 565, in __init__
    from librosa import filters
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\lib\site-packages\lazy_loader\__init__.py", line 74, in __getattr__
    return importlib.import_module(f"{package_name}.{name}")
  File "C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\lib\site-packages\librosa\filters.py", line 52, in <module>
    from numba import jit
  File "C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\np\ufunc\__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "C:\Users\MSI-NB\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\np\ufunc\decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

```

**Comment by tin2tin** [comment]
I'm getting the same error. How did you solve it?
