### ISSUE TITLE
FFMPEG not found?

### ISSUE THREAD

**Issue by Dibucci** [facebookresearch/audiocraft#155]
I don't understand code that much and I've looked and i can't seam to find my issue in the issue's log, unless im blind which wouldn't surprise me tbh, but I was able to get the webui to work and loaded up, the models load up fine and start to generate the song, but as soon as it finishes loading, I get this:

CLIPPING C:\Users\Owner\AppData\Local\Temp\tmpi5npcijd.wav happening with proba (a bit of clipping is okay): 2.0833333564951317e-06 maximum scale:  1.0978285074234009
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Users\Owner\Music\MusicGen\audiocraft\app.py", line 83, in make_waveform
    out = gr.make_waveform(*args, **kwargs)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\helpers.py", line 789, in make_waveform
    raise RuntimeError("ffmpeg not found.")
RuntimeError: ffmpeg not found.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1389, in process_api
    result = await self.call_function(
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1094, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\Owner\Music\MusicGen\audiocraft\app.py", line 167, in predict_full
    outs = _do_predictions(
  File "C:\Users\Owner\Music\MusicGen\audiocraft\app.py", line 132, in _do_predictions
    res = [out_file.result() for out_file in out_files]
  File "C:\Users\Owner\Music\MusicGen\audiocraft\app.py", line 132, in <listcomp>
    res = [out_file.result() for out_file in out_files]
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
RuntimeError: ffmpeg not found.

this is what is plastered on my cmd window and idk fully what any of it means... I'm using the same version of Python I'm using for Stable Diffusion, so I'm hoping I don't need to learn how to have and use multiple instances of Python cuz I've tried that in the past and it was a pain in the rear end for my dumb...ahem, anyhow, I've followed the install instructions to a T from a YT video showing me how to install this and a link ofc to this gitub for any future info needed. due note, I've tried this on both the small, medium, and large models and all have come back with the same lines of errors.

I'm at a loss since I don't understand python one bit, but still test them out cuz I've been loving AI and even if I get errors, at least I can send that to the devs of a project and hope they can fix it for me and any future people who may have the same issue.

my internals are:
RTX 4070 TI 12Gb VRAM
64GB of RAM
11th Gen Intel i9-11900KF @ 3.50GHz 16 logic processers
Windows 11 Pro
and a bit over 9Tb of total storage, with the program being stored and run off of a SSD

If you need more info, plz let me know by telling me what info you need and how and where I can find it either in the programs files or on my PC

**Comment by PeterQJ** [comment]
Can confirm the same issue. I also am using the same instance of python and py torch that I use for Stable Diffusion and would like to avoid multiple installations. I use Audacity as well, which relies on FFmpeg and so I have it installed for Audacity purposes. If you don't have it installed at all, you can find it on GitHub here: https://github.com/BtbN/FFmpeg-Builds/releases

For me, I think it's just a matter of telling AudioCraft where to find FFmpeg on my machine. Trying to figure that out now.

**Comment by PeterQJ** [comment]
I figured it out! You'll need to install ffmpeg. It's different for Windows than for Linux/MacOS. I found this guide most helpful: https://windowsloop.com/install-ffmpeg-windows-10/. You'll need to download and unzip ffmpeg and then create the path for audiocraft to read.

**Comment by FurkanGozukara** [comment]
you need to manually install

i have shown this in my tutorial

here up to date tutorial > https://github.com/facebookresearch/audiocraft/issues/183
