### ISSUE TITLE
Cannot get the models to load / demo to function locally - cannot import name MusicGen, 'MultiBandDiffusion' from 'audiocraft.models

### ISSUE THREAD

**Issue by JayDeeRC** [facebookresearch/audiocraft#160]
File "musicgen_app.py", line 25, in <module>
    from audiocraft.models import MusicGen, MultiBandDiffusion
ImportError: cannot import name 'MultiBandDiffusion' from 'audiocraft.models' (C:\directory\main\anaconda3\envs\my_env\lib\site-packages\audiocraft\models\__init__.py)

**Comment by tyson-ni** [comment]
I get the same error when trying to `from audiocraft.models import MultiBandDiffusion `

**Comment by ashleykleynhans** [comment]
I have not tried this on Windows but it works fine on Linux.

**Comment by Ge-te** [comment]
This worked for me:
`pip uninstall audiocraft`
`pip install -U git+https://git@github.com/facebookresearch/audiocraft#egg=audiocraft`

**Comment by FurkanGozukara** [comment]
here up to date tutorial > https://github.com/facebookresearch/audiocraft/issues/183

their written instructions are incomplete

**Comment by k-a-s-o-u** [comment]
> 



> You need to install the latest version This worked for me: `pip uninstall audiocraft` `pip install -U git+https://git@github.com/facebookresearch/audiocraft#egg=audiocraft`

uninstalled audiocraft then backed to this error
(audiocraft_venv) D:\audiocraft>python .\demos\musicgen_app.py
Traceback (most recent call last):
  File "D:\audiocraft\demos\musicgen_app.py", line 23, in <module>
    from audiocraft.data.audio_utils import convert_audio
ModuleNotFoundError: No module named 'audiocraft'

How can I solve this endless loop?

**Comment by fahnub** [comment]
updating to latest version resolved the issue for me.

**Comment by zeke-john** [comment]
Any update?
