### ISSUE TITLE
Multi-GPU training crashes with `RuntimeError: Tensors must be CUDA and dense`

### ISSUE THREAD

**Issue by carlthome** [facebookresearch/audiocraft#171]
This works for me: `dora run solver=musicgen/debug dset=audio/example dataset.num_workers=0` on c5157b5bf14bf83449c17ea1eeb66c19fb4bc7f0 but multi-GPU training crashes unexpectedly.

```
(py39) jupyter@vm-c75aecd3-0869-4ec7-86f2-9a14f7e772e2:~$ bash train.sh 
Dora directory: /tmp/audiocraft_jupyter
Executor: Starting 4 worker processes for DDP.
Dora directory: /tmp/audiocraft_jupyter
/opt/conda/envs/py39/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
[08-03 14:13:13][torch.distributed.distributed_c10d][INFO] - Added key: store_based_barrier_key:1 to store for rank: 0
[08-03 14:13:13][torch.distributed.distributed_c10d][INFO] - Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 4 nodes.
[08-03 14:13:13][dora.distrib][INFO] - Distributed init: 0/4 (local 0) from env
[08-03 14:13:13][flashy.solver][INFO] - Instantiating solver MusicGenSolver for XP cb9f99a7
[08-03 14:13:13][flashy.solver][INFO] - All XP logs are stored in /tmp/audiocraft_jupyter/xps/cb9f99a7
/opt/conda/envs/py39/lib/python3.9/site-packages/flashy/loggers/tensorboard.py:47: UserWarning: tensorboard package was not found: use pip install tensorboard
  warnings.warn("tensorboard package was not found: use pip install tensorboard")
[08-03 14:13:13][audiocraft.solvers.builders][INFO] - Loading audio data split train: /home/jupyter/audiocraft/egs/example
[08-03 14:13:13][audiocraft.solvers.builders][INFO] - Loading audio data split valid: /home/jupyter/audiocraft/egs/example
[08-03 14:13:13][audiocraft.solvers.builders][INFO] - Loading audio data split evaluate: /home/jupyter/audiocraft/egs/example
[08-03 14:13:13][audiocraft.solvers.builders][INFO] - Loading audio data split generate: /home/jupyter/audiocraft/egs/example
[08-03 14:13:13][root][INFO] - Getting pretrained compression model for debug
{'n_filters': 4, 'n_residual_layers': 1, 'dimension': 32, 'ratios': [10, 8, 16]}
Error executing job with overrides: ['solver=musicgen/debug', 'dset=audio/example', 'dataset.num_workers=0']
Traceback (most recent call last):
  File "/opt/conda/envs/py39/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/py39/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/dora/__main__.py", line 174, in <module>
    main()
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/dora/__main__.py", line 170, in main
    args.action(args, main)
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/dora/run.py", line 69, in run_action
    main()
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/dora/main.py", line 86, in __call__
    return self._main()
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/dora/hydra.py", line 228, in _main
    return hydra.main(
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/jupyter/audiocraft/audiocraft/train.py", line 133, in main
    solver = get_solver(cfg)
  File "/home/jupyter/audiocraft/audiocraft/train.py", line 47, in get_solver
    solver = solvers.get_solver(cfg)
  File "/home/jupyter/audiocraft/audiocraft/solvers/builders.py", line 56, in get_solver
    return klass(cfg)  # type: ignore
  File "/home/jupyter/audiocraft/audiocraft/solvers/musicgen.py", line 38, in __init__
    super().__init__(cfg)
  File "/home/jupyter/audiocraft/audiocraft/solvers/base.py", line 79, in __init__
    self.build_model()
  File "/home/jupyter/audiocraft/audiocraft/solvers/musicgen.py", line 116, in build_model
    self.compression_model = CompressionSolver.wrapped_model_from_checkpoint(
  File "/home/jupyter/audiocraft/audiocraft/solvers/compression.py", line 315, in wrapped_model_from_checkpoint
    compression_model = CompressionSolver.model_from_checkpoint(checkpoint_path, device)
  File "/home/jupyter/audiocraft/audiocraft/solvers/compression.py", line 284, in model_from_checkpoint
    return models.CompressionModel.get_pretrained(name, device)
  File "/home/jupyter/audiocraft/audiocraft/models/encodec.py", line 112, in get_pretrained
    model = builders.get_debug_compression_model()
  File "/home/jupyter/audiocraft/audiocraft/models/builders.py", line 204, in get_debug_compression_model
    quantizer(init_x, 1)  # initialize kmeans etc.
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jupyter/audiocraft/audiocraft/quantization/vq.py", line 81, in forward
    quantized, codes, commit_loss = self.vq(x, n_q=n_q)
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jupyter/audiocraft/audiocraft/quantization/core_vq.py", line 373, in forward
    quantized, indices, loss = layer(residual)
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jupyter/audiocraft/audiocraft/quantization/core_vq.py", line 318, in forward
    quantize, embed_ind = self._codebook(x)
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jupyter/audiocraft/audiocraft/quantization/core_vq.py", line 198, in forward
    self.init_embed_(x)
  File "/home/jupyter/audiocraft/audiocraft/quantization/core_vq.py", line 140, in init_embed_
    flashy.distrib.broadcast_tensors(self.buffers())
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/flashy/distrib.py", line 121, in broadcast_tensors
    _check_number_of_params(tensors)
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/flashy/distrib.py", line 84, in _check_number_of_params
    all_reduce(tensor)
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/flashy/distrib.py", line 47, in all_reduce
    return distributed.all_reduce(tensor, op)
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/py39/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1700, in all_reduce
    work = default_pg.allreduce([tensor], opts)
RuntimeError: Tensors must be CUDA and dense
Executor: Worker 1 died, killing all workers
Executor: Worker 2 died, killing all workers
Executor: Worker 3 died, killing all workers
```

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P0    45W / 300W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:00:05.0 Off |                    0 |
| N/A   37C    P0    57W / 300W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:00:06.0 Off |                    0 |
| N/A   38C    P0    48W / 300W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:00:07.0 Off |                    0 |
| N/A   39C    P0    57W / 300W |      0MiB / 16384MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by didadida-r** [comment]
@carlthome hi, i am wondering how to train the model in DDP way, i start training with cmd 
`dora run solver=musicgen/debug dset=audio/example dataset.num_workers=0`
but it only train only single gpu:0 without ddp

'''
Dora directory: ./exp
/home/test/python_env/anaconda3/envs/audiocraft_py39/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
[08-09 10:37:22][dora.distrib][INFO] - world_size is 1, skipping init.
[08-09 10:37:22][flashy.solver][INFO] - Instantiating solver MusicGenSolver for XP cb9f99a7
/home/test/python_env/anaconda3/envs/audiocraft_py39/lib/python3.9/site-packages/flashy/loggers/tensorboard.py:47: UserWarning: tensorboard package was not found: use pip install tensorboard
  warnings.warn("tensorboard package was not found: use pip install tensorboard")
[08-09 10:37:22][audiocraft.solvers.builders][INFO] - Loading audio data split train: /home/test/code/git_code/audiocraft/egs/example
[08-09 10:37:23][audiocraft.solvers.builders][INFO] - Loading audio data split valid: /home/test/code/git_code/audiocraft/egs/example
[08-09 10:37:23][audiocraft.solvers.builders][INFO] - Loading audio data split evaluate: /home/test/code/git_code/audiocraft/egs/example
[08-09 10:37:24][audiocraft.solvers.builders][INFO] - Loading audio data split generate: /home/test/code/git_code/audiocraft/egs/example
[08-09 10:37:24][root][INFO] - Getting pretrained compression model for debug
{'n_filters': 4, 'n_residual_layers': 1, 'dimension': 32, 'ratios': [10, 8, 16]}
[08-09 10:37:39][flashy.solver][INFO] - Compression model has 4 codebooks with 400 cardinality, and a framerate of 25
[08-09 10:37:39][audiocraft.modules.conditioners][INFO] - T5 will be evaluated with autocast as float32
'''

**Comment by carlthome** [comment]
@didadida-r try `-d` as per https://github.com/facebookresearch/dora#dora-run-running-xp-locally

**Comment by Maggione** [comment]
> @didadida-r try `-d` as per https://github.com/facebookresearch/dora#dora-run-running-xp-locally

Hello, can you share your script? 

I have 8 GPUs and my script is as following:
```
dora run -d solver=musicgen/musicgen_base_32khz model/lm/model_scale=small continue_from=//pretrained/facebook/musicgen-small conditioner=text2music
```
however, it always find only one worker:
```
[�[36m08-17 10:28:15�[0m][�[34mroot�[0m][�[32mINFO�[0m] - Getting pretrained compression model from HF facebook/encodec_32khz�[0m
[�[36m08-17 10:28:13�[0m][�[34mdora.distrib�[0m][�[32mINFO�[0m] - world_size is 1, skipping init.�[0m
[�[36m08-17 10:28:13�[0m][�[34mflashy.solver�[0m][�[32mINFO�[0m] - Instantiating solver MusicGenSolver for XP 4284c302�[0m
```
Thank you very much!
