### ISSUE TITLE
musicgen_app will not launch on local clone:

### ISSUE THREAD

**Issue by moon47usaco** [facebookresearch/audiocraft#175]
I have the old 0.0.02a working in another location.

Install without errors using [ pip install -e . ]

Running the musicgen app complains of dependencies.

```
S:\Ai\Repos\audiocraft>python -m demos.musicgen_app --share
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Traceback (most recent call last):
  File "C:\Users\moon4\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\moon4\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "S:\Ai\Repos\audiocraft\demos\musicgen_app.py", line 23, in <module>
    from audiocraft.data.audio_utils import convert_audio
  File "S:\Ai\Repos\audiocraft\audiocraft\__init__.py", line 24, in <module>
    from . import data, modules, models
  File "S:\Ai\Repos\audiocraft\audiocraft\data\__init__.py", line 10, in <module>
    from . import audio, audio_dataset, info_audio_dataset, music_dataset, sound_dataset
  File "S:\Ai\Repos\audiocraft\audiocraft\data\info_audio_dataset.py", line 19, in <module>
    from ..modules.conditioners import SegmentWithAttributes, ConditioningAttributes
  File "S:\Ai\Repos\audiocraft\audiocraft\modules\conditioners.py", line 22, in <module>
    from transformers import RobertaTokenizer, T5EncoderModel, T5Tokenizer  # type: ignore
  File "C:\Users\moon4\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Users\moon4\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dependency_versions_check.py", line 57, in <module>
    require_version_core(deps[pkg])
  File "C:\Users\moon4\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\versions.py", line 117, in require_version_core
    return require_version(requirement, hint)
  File "C:\Users\moon4\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\versions.py", line 111, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "C:\Users\moon4\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\versions.py", line 44, in _compare_versions
    raise ImportError(
ImportError: accelerate>=0.20.3 is required for a normal functioning of this module, but found accelerate==0.19.0.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
```

**Comment by FurkanGozukara** [comment]
here up to date tutorial

their written instructions are incomplete 

https://github.com/facebookresearch/audiocraft/issues/183
