### ISSUE TITLE
Question about ErrMsg : No module named torch

### ISSUE THREAD

**Issue by phdhorse41** [facebookresearch/audiocraft#179]
I’ve installed Pytorch 2.0 successfully, but still I got this errmsg while I am trying to install Audiocraft. The errmsg are listed in the following content.

 

Collecting xformers (from audiocraft)

  Using cached xformers-0.0.16.tar.gz (7.3 MB)

  Installing build dependencies ... done

  Getting requirements to build wheel ... error

  error: subprocess-exited-with-error

 

  × Getting requirements to build wheel did not run successfully.

  │ exit code: 1

  ╰─> [21 lines of output]

      Traceback (most recent call last):

        File "D:\python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>

          main()

        File "D:\python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main

          json_out['return_val'] = hook(**hook_input['kwargs'])

                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        File "D:\python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel

          return hook(config_settings)

                 ^^^^^^^^^^^^^^^^^^^^^

        File "C:\Users\mazhuoyi\AppData\Local\Temp\pip-build-env-2alxz8az\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel

          return self._get_build_requires(config_settings, requirements=['wheel'])

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        File "C:\Users\mazhuoyi\AppData\Local\Temp\pip-build-env-2alxz8az\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires

          self.run_setup()

        File "C:\Users\mazhuoyi\AppData\Local\Temp\pip-build-env-2alxz8az\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup

          self).run_setup(setup_script=setup_script)

                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        File "C:\Users\mazhuoyi\AppData\Local\Temp\pip-build-env-2alxz8az\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup

          exec(code, locals())

        File "<string>", line 23, in <module>

      ModuleNotFoundError: No module named 'torch'

      [end of output]

 

  note: This error originates from a subprocess, and is likely not a problem with pip.

error: subprocess-exited-with-error

 

× Getting requirements to build wheel did not run successfully.

│ exit code: 1

╰─> See above for output.

 

note: This error originates from a subprocess, and is likely not a problem with pip.

It seems to be the problem with xformers as the errmsg given.

**Comment by saikoaizen** [comment]
- Do you have multiple versions of python?
- Did you install PyTorch through pip?

**Comment by FurkanGozukara** [comment]
here up to date tutorial

their written instructions are incomplete 

https://github.com/facebookresearch/audiocraft/issues/183
