### ISSUE TITLE
Gradio module not found?

### ISSUE THREAD

**Issue by lebakerino** [facebookresearch/audiocraft#199]
Hi, I am trying to install this but getting the below error, I used the guide by 'SECourses' (Furkan) who I believe is active here, maybe if you see this you may be able to advise. I've followed the instructions yet I am getting the below error when running the commands to attempt to launch the app. 

Any advice? Thanks.

C:\metamusic\audiocraft>call .\venv\Scripts\activate.bat

(venv) C:\metamusic\audiocraft>python .\demos\musicgen_app.py --inbrowser
Traceback (most recent call last):
  File "C:\metamusic\audiocraft\demos\musicgen_app.py", line 21, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

(venv) C:\metamusic\audiocraft>

**Comment by FurkanGozukara** [comment]
> Hi, I am trying to install this but getting the below error, I used the guide by 'SECourses' (Furkan) who I believe is active here, maybe if you see this you may be able to advise. I've followed the instructions yet I am getting the below error when running the commands to attempt to launch the app.
> 
> Any advice? Thanks.
> 
> C:\metamusic\audiocraft>call .\venv\Scripts\activate.bat
> 
> (venv) C:\metamusic\audiocraft>python .\demos\musicgen_app.py --inbrowser Traceback (most recent call last): File "C:\metamusic\audiocraft\demos\musicgen_app.py", line 21, in import gradio as gr ModuleNotFoundError: No module named 'gradio'
> 
> (venv) C:\metamusic\audiocraft>

well the requirements have gradio > https://github.com/facebookresearch/audiocraft/blob/main/requirements.txt

are you using latest commit?

you can do this activate venv and
pip install gradio

**Comment by lebakerino** [comment]
> > Hi, I am trying to install this but getting the below error, I used the guide by 'SECourses' (Furkan) who I believe is active here, maybe if you see this you may be able to advise. I've followed the instructions yet I am getting the below error when running the commands to attempt to launch the app.
> > Any advice? Thanks.
> > C:\metamusic\audiocraft>call .\venv\Scripts\activate.bat
> > (venv) C:\metamusic\audiocraft>python .\demos\musicgen_app.py --inbrowser Traceback (most recent call last): File "C:\metamusic\audiocraft\demos\musicgen_app.py", line 21, in import gradio as gr ModuleNotFoundError: No module named 'gradio'
> > (venv) C:\metamusic\audiocraft>
> 
> well the requirements have gradio > https://github.com/facebookresearch/audiocraft/blob/main/requirements.txt
> 
> are you using latest commit?
> 
> you can do this activate venv and pip install gradio

Thanks for response, I was using the latest that was pulled from git, no idea what was going on, decided to just try Ponikio to install it and it worked.

Cheers.
