### ISSUE TITLE
Why is this error reported?

### ISSUE THREAD

**Issue by gg22mm** [facebookresearch/audiocraft#248]
(py3.10) E:\wll\phpsys\WWW\start\l__dzkj_test\test\resnet\pytorch\txt\音乐\audiocraft\1>dora run solver=musicgen/musicgen_base_32khz
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Traceback (most recent call last):
  File "d:\Anaconda3\envs\py3.10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\Anaconda3\envs\py3.10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "d:\Anaconda3\envs\py3.10\Scripts\dora.exe\__main__.py", line 7, in <module>
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\dora\__main__.py", line 158, in main
    main = get_main(args.main_module, args.package)
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\dora\_utils.py", line 48, in get_main
    module = import_or_fatal(module_name)
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\dora\utils.py", line 77, in import_or_fatal
    return importlib.import_module(module_name)
  File "d:\Anaconda3\envs\py3.10\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\wll\phpsys\WWW\start\l__dzkj_test\test\resnet\pytorch\txt\音乐\audiocraft\1\audiocraft\train.py", line 125, in <module>
    def main(cfg):
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\dora\hydra.py", line 308, in _decorator
    return HydraMain(main, config_name=config_name, config_path=config_path,
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\dora\hydra.py", line 163, in __init__
    dora = self._get_dora()
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\dora\hydra.py", line 173, in _get_dora
    update_from_hydra(dora, self._base_cfg.dora)
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\dora\conf.py", line 35, in update_from_hydra
    dct = OmegaConf.to_container(cfg, resolve=True)
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\omegaconf.py", line 573, in to_container
    return BaseContainer._to_content(
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\basecontainer.py", line 292, in _to_content
    value = get_node_value(key)
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\basecontainer.py", line 244, in get_node_value
    conf._format_and_raise(key=key, value=None, cause=e)
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\base.py", line 231, in _format_and_raise
    format_and_raise(
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\basecontainer.py", line 242, in get_node_value
    node = node._dereference_node()
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\base.py", line 246, in _dereference_node
    node = self._dereference_node_impl(throw_on_resolution_failure=True)
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\base.py", line 277, in _dereference_node_impl
    return parent._resolve_interpolation_from_parse_tree(
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\base.py", line 584, in _resolve_interpolation_from_parse_tree
    resolved = self.resolve_parse_tree(
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\base.py", line 769, in resolve_parse_tree
    raise InterpolationResolutionError(
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\base.py", line 764, in resolve_parse_tree
    return visitor.visit(parse_tree)
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\antlr4\tree\Tree.py", line 34, in visit
    return tree.accept(self)
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\grammar\gen\OmegaConfGrammarParser.py", line 206, in accept
    return visitor.visitConfigValue(self)
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\grammar_visitor.py", line 101, in visitConfigValue
    return self.visit(ctx.getChild(0))
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\antlr4\tree\Tree.py", line 34, in visit
    return tree.accept(self)
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\grammar\gen\OmegaConfGrammarParser.py", line 342, in accept
    return visitor.visitText(self)
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\grammar_visitor.py", line 301, in visitText
    return self._unescape(list(ctx.getChildren()))
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\grammar_visitor.py", line 389, in _unescape
    text = str(self.visitInterpolation(node))
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\grammar_visitor.py", line 125, in visitInterpolation
    return self.visit(ctx.getChild(0))
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\antlr4\tree\Tree.py", line 34, in visit
    return tree.accept(self)
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\grammar\gen\OmegaConfGrammarParser.py", line 1041, in accept
    return visitor.visitInterpolationResolver(self)
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\grammar_visitor.py", line 179, in visitInterpolationResolver
    return self.resolver_interpolation_callback(
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\base.py", line 750, in resolver_interpolation_callback
    return self._evaluate_custom_resolver(
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\base.py", line 694, in _evaluate_custom_resolver
    return resolver(
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\omegaconf.py", line 445, in resolver_wrapper
    ret = resolver(*args, **kwargs)
  File "d:\Anaconda3\envs\py3.10\lib\site-packages\omegaconf\resolvers\oc\__init__.py", line 38, in env
    raise KeyError(f"Environment variable '{key}' not found")
omegaconf.errors.InterpolationResolutionError: KeyError raised while resolving interpolation: "Environment variable 'USER' not found"
    full_key: dora.dir
    object_type=dict

![图片](https://github.com/facebookresearch/audiocraft/assets/6648329/0574876b-e181-4d7f-a275-fd5e438fe752)

**Comment by Charlottecuc** [comment]
`export USER="$(whoami)"`

**Comment by gg22mm** [comment]
Thank you for your reply. I think Windows seems somewhat incompatible.
