### ISSUE TITLE
error with torchaudio.pyd

### ISSUE THREAD

**Issue by Eldiablozzz** [facebookresearch/audiocraft#30]
I have everything installed without errors still i cant run it. This is the error i get when i run app.py:
E:\audiocraft>python app.py
Traceback (most recent call last):
  File "E:\audiocraft\app.py", line 11, in <module>
    from audiocraft.models import MusicGen
  File "E:\audiocraft\audiocraft\__init__.py", line 8, in <module>
    from . import data, modules, models
  File "E:\audiocraft\audiocraft\data\__init__.py", line 8, in <module>
    from . import audio, audio_dataset
  File "E:\audiocraft\audiocraft\data\audio.py", line 21, in <module>
    import torchaudio as ta
  File "E:\Python\Python310\lib\site-packages\torchaudio\__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "E:\Python\Python310\lib\site-packages\torchaudio\_extension\__init__.py", line 43, in <module>
    _load_lib("libtorchaudio")
  File "E:\Python\Python310\lib\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "E:\Python\Python310\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "E:\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'E:\Python\Python310\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by rengezri** [comment]
had the same libtorchaudio.pyd error message when cuda was not installed on torch and torchaudio. after deinstalling torch and reinstalling i got it working with:

Windows 10 - CUDA 117
torch 2.01+cu117
torchaudio 2.02+cu117
torchvision 0.15.2+cu117

**Comment by Eldiablozzz** [comment]
> had the same libtorchaudio.pyd error message when cuda was not installed on torch and torchaudio. after deinstalling torch and reinstalling i got it working with:
> 
> Windows 10 - CUDA 117 torch 2.01+cu117 torchaudio 2.02+cu117 torchvision 0.15.2+cu117

Thanks already reinstalling it, funny thing is it writes as installed with cuda and still makes it cpu version.
