### ISSUE TITLE
Urgent fix needed you have broken something - related to some package xformers version

### ISSUE THREAD

**Issue by FurkanGozukara** [facebookresearch/audiocraft#304]
```
(venv) G:\temp7\audiocraft>pip install -U audiocraft
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting audiocraft
  Downloading audiocraft-1.0.0.tar.gz (609 kB)
     ---------------------------------------- 609.1/609.1 kB 2.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: av in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (10.0.0)
Requirement already satisfied: einops in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (0.7.0)
Requirement already satisfied: flashy>=0.0.1 in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (0.0.2)
Requirement already satisfied: hydra-core>=1.1 in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (1.3.2)
Requirement already satisfied: hydra_colorlog in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (1.2.0)
Requirement already satisfied: julius in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (0.2.7)
Requirement already satisfied: num2words in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (0.5.12)
Requirement already satisfied: numpy in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (1.25.2)
Requirement already satisfied: sentencepiece in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (0.1.99)
Requirement already satisfied: spacy==3.5.2 in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (3.5.2)
Requirement already satisfied: torch>=2.0.0 in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (2.1.0+cu118)
Requirement already satisfied: torchaudio>=2.0.0 in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (2.1.0+cu118)
Requirement already satisfied: huggingface_hub in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (0.17.3)
Requirement already satisfied: tqdm in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (4.66.1)
Collecting transformers>=4.31.0
  Downloading transformers-4.34.0-py3-none-any.whl (7.7 MB)
     ---------------------------------------- 7.7/7.7 MB 26.1 MB/s eta 0:00:00
Requirement already satisfied: xformers in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (0.0.22)
Requirement already satisfied: demucs in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (4.0.1)
Requirement already satisfied: librosa in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (0.10.1)
Requirement already satisfied: gradio in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (3.47.1)
Requirement already satisfied: torchmetrics in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (1.2.0)
Requirement already satisfied: encodec in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (0.1.1)
Requirement already satisfied: protobuf in g:\temp7\audiocraft\venv\lib\site-packages (from audiocraft) (4.24.4)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (2.0.10)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4 in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (1.10.13)
Requirement already satisfied: pathy>=0.10.0 in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (0.10.2)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (1.0.5)
Requirement already satisfied: jinja2 in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (3.1.2)
Requirement already satisfied: packaging>=20.0 in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (23.2)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (1.0.10)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (3.0.12)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (1.1.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (3.3.0)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (3.0.9)
Requirement already satisfied: thinc<8.2.0,>=8.1.8 in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (8.1.12)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (2.4.8)
Requirement already satisfied: typer<0.8.0,>=0.3.0 in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (0.7.0)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (2.0.8)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (2.31.0)
Requirement already satisfied: setuptools in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (65.5.0)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in g:\temp7\audiocraft\venv\lib\site-packages (from spacy==3.5.2->audiocraft) (6.4.0)
Requirement already satisfied: colorlog in g:\temp7\audiocraft\venv\lib\site-packages (from flashy>=0.0.1->audiocraft) (6.7.0)
Requirement already satisfied: dora-search in g:\temp7\audiocraft\venv\lib\site-packages (from flashy>=0.0.1->audiocraft) (0.1.12)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in g:\temp7\audiocraft\venv\lib\site-packages (from hydra-core>=1.1->audiocraft) (4.9.3)
Requirement already satisfied: omegaconf<2.4,>=2.2 in g:\temp7\audiocraft\venv\lib\site-packages (from hydra-core>=1.1->audiocraft) (2.3.0)
Requirement already satisfied: networkx in g:\temp7\audiocraft\venv\lib\site-packages (from torch>=2.0.0->audiocraft) (3.1)
Requirement already satisfied: fsspec in g:\temp7\audiocraft\venv\lib\site-packages (from torch>=2.0.0->audiocraft) (2023.9.2)
Requirement already satisfied: filelock in g:\temp7\audiocraft\venv\lib\site-packages (from torch>=2.0.0->audiocraft) (3.12.4)
Requirement already satisfied: sympy in g:\temp7\audiocraft\venv\lib\site-packages (from torch>=2.0.0->audiocraft) (1.12)
Requirement already satisfied: typing-extensions in g:\temp7\audiocraft\venv\lib\site-packages (from torch>=2.0.0->audiocraft) (4.8.0)
Requirement already satisfied: colorama in g:\temp7\audiocraft\venv\lib\site-packages (from tqdm->audiocraft) (0.4.6)
Collecting safetensors>=0.3.1
  Downloading safetensors-0.4.0-cp310-none-win_amd64.whl (277 kB)
     ---------------------------------------- 277.4/277.4 kB ? eta 0:00:00
Collecting regex!=2019.12.17
  Downloading regex-2023.10.3-cp310-cp310-win_amd64.whl (269 kB)
     ---------------------------------------- 269.6/269.6 kB ? eta 0:00:00
Requirement already satisfied: pyyaml>=5.1 in g:\temp7\audiocraft\venv\lib\site-packages (from transformers>=4.31.0->audiocraft) (6.0.1)
Collecting tokenizers<0.15,>=0.14
  Downloading tokenizers-0.14.1-cp310-none-win_amd64.whl (2.2 MB)
     ---------------------------------------- 2.2/2.2 MB 34.7 MB/s eta 0:00:00
Requirement already satisfied: lameenc>=1.2 in g:\temp7\audiocraft\venv\lib\site-packages (from demucs->audiocraft) (1.6.1)
Requirement already satisfied: openunmix in g:\temp7\audiocraft\venv\lib\site-packages (from demucs->audiocraft) (1.2.1)
Requirement already satisfied: aiofiles<24.0,>=22.0 in g:\temp7\audiocraft\venv\lib\site-packages (from gradio->audiocraft) (23.2.1)
Requirement already satisfied: markupsafe~=2.0 in g:\temp7\audiocraft\venv\lib\site-packages (from gradio->audiocraft) (2.1.3)
Requirement already satisfied: importlib-resources<7.0,>=1.3 in g:\temp7\audiocraft\venv\lib\site-packages (from gradio->audiocraft) (6.1.0)
Requirement already satisfied: pandas<3.0,>=1.0 in g:\temp7\audiocraft\venv\lib\site-packages (from gradio->audiocraft) (2.1.1)
Requirement already satisfied: python-multipart in g:\temp7\audiocraft\venv\lib\site-packages (from gradio->audiocraft) (0.0.6)
Requirement already satisfied: orjson~=3.0 in g:\temp7\audiocraft\venv\lib\site-packages (from gradio->audiocraft) (3.9.7)
Requirement already satisfied: pillow<11.0,>=8.0 in g:\temp7\audiocraft\venv\lib\site-packages (from gradio->audiocraft) (10.0.1)
Requirement already satisfied: semantic-version~=2.0 in g:\temp7\audiocraft\venv\lib\site-packages (from gradio->audiocraft) (2.10.0)
Requirement already satisfied: websockets<12.0,>=10.0 in g:\temp7\audiocraft\venv\lib\site-packages (from gradio->audiocraft) (11.0.3)
Requirement already satisfied: altair<6.0,>=4.2.0 in g:\temp7\audiocraft\venv\lib\site-packages (from gradio->audiocraft) (5.1.2)
Requirement already satisfied: uvicorn>=0.14.0 in g:\temp7\audiocraft\venv\lib\site-packages (from gradio->audiocraft) (0.23.2)
Requirement already satisfied: fastapi in g:\temp7\audiocraft\venv\lib\site-packages (from gradio->audiocraft) (0.103.2)
Requirement already satisfied: httpx in g:\temp7\audiocraft\venv\lib\site-packages (from gradio->audiocraft) (0.25.0)
Requirement already satisfied: matplotlib~=3.0 in g:\temp7\audiocraft\venv\lib\site-packages (from gradio->audiocraft) (3.8.0)
Requirement already satisfied: ffmpy in g:\temp7\audiocraft\venv\lib\site-packages (from gradio->audiocraft) (0.3.1)
Requirement already satisfied: pydub in g:\temp7\audiocraft\venv\lib\site-packages (from gradio->audiocraft) (0.25.1)
Requirement already satisfied: gradio-client==0.6.0 in g:\temp7\audiocraft\venv\lib\site-packages (from gradio->audiocraft) (0.6.0)
Requirement already satisfied: scipy>=1.2.0 in g:\temp7\audiocraft\venv\lib\site-packages (from librosa->audiocraft) (1.11.3)
Requirement already satisfied: pooch>=1.0 in g:\temp7\audiocraft\venv\lib\site-packages (from librosa->audiocraft) (1.7.0)
Requirement already satisfied: scikit-learn>=0.20.0 in g:\temp7\audiocraft\venv\lib\site-packages (from librosa->audiocraft) (1.3.1)
Requirement already satisfied: decorator>=4.3.0 in g:\temp7\audiocraft\venv\lib\site-packages (from librosa->audiocraft) (5.1.1)
Requirement already satisfied: lazy-loader>=0.1 in g:\temp7\audiocraft\venv\lib\site-packages (from librosa->audiocraft) (0.3)
Requirement already satisfied: numba>=0.51.0 in g:\temp7\audiocraft\venv\lib\site-packages (from librosa->audiocraft) (0.58.0)
Requirement already satisfied: msgpack>=1.0 in g:\temp7\audiocraft\venv\lib\site-packages (from librosa->audiocraft) (1.0.7)
Requirement already satisfied: joblib>=0.14 in g:\temp7\audiocraft\venv\lib\site-packages (from librosa->audiocraft) (1.3.2)
Requirement already satisfied: soxr>=0.3.2 in g:\temp7\audiocraft\venv\lib\site-packages (from librosa->audiocraft) (0.3.7)
Requirement already satisfied: soundfile>=0.12.1 in g:\temp7\audiocraft\venv\lib\site-packages (from librosa->audiocraft) (0.12.1)
Requirement already satisfied: audioread>=2.1.9 in g:\temp7\audiocraft\venv\lib\site-packages (from librosa->audiocraft) (3.0.1)
Requirement already satisfied: docopt>=0.6.2 in g:\temp7\audiocraft\venv\lib\site-packages (from num2words->audiocraft) (0.6.2)
Requirement already satisfied: lightning-utilities>=0.8.0 in g:\temp7\audiocraft\venv\lib\site-packages (from torchmetrics->audiocraft) (0.9.0)
Collecting xformers
  Downloading xformers-0.0.21-cp310-cp310-win_amd64.whl (97.5 MB)
     ---------------------------------------- 97.5/97.5 MB 31.2 MB/s eta 0:00:00
  Downloading xformers-0.0.20-cp310-cp310-win_amd64.whl (97.6 MB)
     ---------------------------------------- 97.6/97.6 MB 29.8 MB/s eta 0:00:00
Collecting pyre-extensions==0.0.29
  Downloading pyre_extensions-0.0.29-py3-none-any.whl (12 kB)
Collecting xformers
  Downloading xformers-0.0.19-cp310-cp310-win_amd64.whl (96.7 MB)
     ---------------------------------------- 96.7/96.7 MB 38.4 MB/s eta 0:00:00
  Downloading xformers-0.0.18-cp310-cp310-win_amd64.whl (112.3 MB)
     ---------------------------------------- 112.3/112.3 MB 38.4 MB/s eta 0:00:00
Collecting pyre-extensions==0.0.23
  Downloading pyre_extensions-0.0.23-py3-none-any.whl (11 kB)
Collecting xformers
  Downloading xformers-0.0.17-cp310-cp310-win_amd64.whl (112.6 MB)
     ---------------------------------------- 112.6/112.6 MB 40.9 MB/s eta 0:00:00
  Downloading xformers-0.0.16-cp310-cp310-win_amd64.whl (40.0 MB)
     ---------------------------------------- 40.0/40.0 MB 40.9 MB/s eta 0:00:00
  Downloading xformers-0.0.13.tar.gz (292 kB)
     ---------------------------------------- 292.5/292.5 kB ? eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\King\AppData\Local\Temp\pip-install-l68acxpv\xformers_b98bfc682e574a6287023d94b12f581f\setup.py", line 239, in <module>
          ext_modules=get_extensions(),
        File "C:\Users\King\AppData\Local\Temp\pip-install-l68acxpv\xformers_b98bfc682e574a6287023d94b12f581f\setup.py", line 157, in get_extensions
          raise RuntimeError(
      RuntimeError: CUTLASS submodule not found. Did you forget to run `git submodule update --init --recursive` ?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by FurkanGozukara** [comment]
ok after working like 2 hours finally figured out

updated my 1 click auto installer and also tutorial github file

[AI Music Generation Audiocraft & MusicGen Tutorial with Example (Free Text-to-Music Model)](https://youtu.be/v-YpvPkhdO4)

1 click auto installer : https://www.patreon.com/posts/84334460 - fully supports CUDA Pytorch and GPU

![image](https://github.com/facebookresearch/audiocraft/assets/19240467/2534834c-3e88-42ec-ab23-dde5d0f2a5e9)

![image](https://github.com/facebookresearch/audiocraft/assets/19240467/6dd0d98c-1d17-4f7c-971a-919e1d2b1a9b)

![image](https://github.com/facebookresearch/audiocraft/assets/19240467/b0be1036-417a-4916-a0c1-b3382d466922)

**Comment by akayhanfar** [comment]
> ok after working like 2 hours finally figured out
> 
> updated my 1 click auto installer and also tutorial github file
> 
> [AI Music Generation Audiocraft & MusicGen Tutorial with Example (Free Text-to-Music Model)](https://youtu.be/v-YpvPkhdO4)
> 
> 1 click auto installer : https://www.patreon.com/posts/84334460 - fully supports CUDA Pytorch and GPU
> 
> ![image](https://user-images.githubusercontent.com/19240467/273417591-2534834c-3e88-42ec-ab23-dde5d0f2a5e9.png)
> 
> ![image](https://user-images.githubusercontent.com/19240467/273417605-6dd0d98c-1d17-4f7c-971a-919e1d2b1a9b.png)
> 
> ![image](https://user-images.githubusercontent.com/19240467/273417614-b0be1036-417a-4916-a0c1-b3382d466922.png)
-------------------------------------------------------
hey I'm getting the same error as you were "CUTLASS something" would you mind sharing how you resolved it? I have watched your video as well but didn't see anything related to this error.

**Comment by ediller3** [comment]
@akayhanfar I was able to get around this issue by installing xformers with Conda:

`conda install xformers -c xformers`

Hope that helps
