### ISSUE TITLE
Using the update method is deprecated. Simply return a new object instead

### ISSUE THREAD

**Issue by rer0dgers** [facebookresearch/audiocraft#319]
I am having so much trouble getting it working the first time. Here are the errors below. I think they're related errors. The TEMP file is created but with zero bytes. 
```
H:\Program Files\Python311\Lib\site-packages\gradio\helpers.py:818: UserWarning: Using the update method is deprecated. Simply return a new object instead, e.g. `return gr.Textbox(...)` instead of `return gr.update(...)
  warnings.warn(
H:\Program Files\Python311\Lib\site-packages\gradio\components\video.py:153: UserWarning: Using the update method is deprecated. Simply return a new object instead, e.g. `return gr.Video(...)` instead of `return gr.Video.update(...)`.
  warnings.warn(
H:\Program Files\Python311\Lib\site-packages\gradio\components\audio.py:167: UserWarning: Using the update method is deprecated. Simply return a new object instead, e.g. `return gr.Audio(...)` instead of `return gr.Audio.update(...)`.
  warnings.warn(
Loading model facebook/musicgen-large
H:\Program Files\Python311\Lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
new batch 1 ['A smooth jazz song with a mellow mid tempo and piano lead'] [None]
Traceback (most recent call last):
  File "h:\music\audiocraft\audiocraft\data\audio.py", line 225, in audio_write
    _piping_to_ffmpeg(path, wav, sample_rate, flags)
  File "h:\music\audiocraft\audiocraft\data\audio.py", line 156, in _piping_to_ffmpeg
    sp.run(command, input=input_, check=True)
  File "H:\Program Files\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Program Files\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "H:\Program Files\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\Program Files\Python311\Lib\site-packages\gradio\queueing.py", line 406, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Program Files\Python311\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Program Files\Python311\Lib\site-packages\gradio\blocks.py", line 1554, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Program Files\Python311\Lib\site-packages\gradio\blocks.py", line 1192, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Program Files\Python311\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Program Files\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "H:\Program Files\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Program Files\Python311\Lib\site-packages\gradio\utils.py", line 659, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "H:\MUSIC\audiocraft\demos\musicgen_app.py", line 187, in predict_full
    videos, wavs = _do_predictions(
                   ^^^^^^^^^^^^^^^^
  File "H:\MUSIC\audiocraft\demos\musicgen_app.py", line 140, in _do_predictions
    audio_write(
  File "h:\music\audiocraft\audiocraft\data\audio.py", line 229, in audio_write
    path.unlink()
  File "H:\Program Files\Python311\Lib\pathlib.py", line 1147, in unlink
    os.unlink(self)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\INSOMN~1\\AppData\\Local\\Temp\\tmpfqf6g_ng.wav'
```

**Comment by rer0dgers** [comment]
![image](https://github.com/facebookresearch/audiocraft/assets/10727648/5c37c7ad-18c8-49e5-a582-2c04c18bab68)

**Comment by rer0dgers** [comment]
Cancel this... ffmpeg was not installed correctly nor in my system PATH. I'm working now..
