### ISSUE TITLE
I got this error 'TypeError: issubclass() arg 1 must be a class'

### ISSUE THREAD

**Issue by Cate9021** [facebookresearch/audiocraft#33]
`Traceback (most recent call last):
  File "C:\musicgen\audiocraft-main\app.py", line 11, in <module>
    from audiocraft.models import MusicGen
  File "C:\musicgen\audiocraft-main\audiocraft\__init__.py", line 8, in <module>
    from . import data, modules, models
  File "C:\musicgen\audiocraft-main\audiocraft\models\__init__.py", line 8, in <module>
    from .musicgen import MusicGen
  File "C:\musicgen\audiocraft-main\audiocraft\models\musicgen.py", line 18, in <module>
    from .lm import LMModel
  File "C:\musicgen\audiocraft-main\audiocraft\models\lm.py", line 18, in <module>
    from ..modules.conditioners import (
  File "C:\musicgen\audiocraft-main\audiocraft\modules\conditioners.py", line 19, in <module>
    import spacy
  File "C:\Users\PC\.conda\envs\musicgen\lib\site-packages\spacy\__init__.py", line 14, in <module>
    from . import pipeline  # noqa: F401
  File "C:\Users\PC\.conda\envs\musicgen\lib\site-packages\spacy\pipeline\__init__.py", line 1, in <module>
    from .attributeruler import AttributeRuler
  File "C:\Users\PC\.conda\envs\musicgen\lib\site-packages\spacy\pipeline\attributeruler.py", line 6, in <module>
    from .pipe import Pipe
  File "spacy\pipeline\pipe.pyx", line 1, in init spacy.pipeline.pipe
  File "spacy\vocab.pyx", line 1, in init spacy.vocab
  File "C:\Users\PC\.conda\envs\musicgen\lib\site-packages\spacy\tokens\__init__.py", line 1, in <module>
    from .doc import Doc
  File "spacy\tokens\doc.pyx", line 36, in init spacy.tokens.doc
  File "C:\Users\PC\.conda\envs\musicgen\lib\site-packages\spacy\schemas.py", line 250, in <module>
    class TokenPattern(BaseModel):
  File "pydantic\main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic\fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic\fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic\fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "C:\Users\PC\.conda\envs\musicgen\lib\typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class`
trying to run it in conda enviroment but failed.

**Comment by Cate9021** [comment]
`File ~\.conda\envs\musicgen1\lib\typing.py:852, in _SpecialGenericAlias.__subclasscheck__(self, cls)
    850     return issubclass(cls.__origin__, self.__origin__)
    851 if not isinstance(cls, _GenericAlias):
--> 852     return issubclass(cls, self.__origin__)
    853 return super().__subclasscheck__(cls)

TypeError: issubclass() arg 1 must be a class`

Same error in Jupyter under conda .env.

**Comment by Cate9021** [comment]
Fixed. By not using Python 3.9 but Python 3.10.11
