### ISSUE TITLE
Do i need to run the slurm cluster for training MusicGen using dora ?

### ISSUE THREAD

**Issue by piyuch** [facebookresearch/audiocraft#342]
`Traceback (most recent call last):
  File "/opt/conda/bin/dora", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/dora/__main__.py", line 170, in main
    args.action(args, main)
  File "/opt/conda/lib/python3.10/site-packages/dora/grid.py", line 138, in grid_action
    run_grid(main, explorer, args.grid, rules, slurm, grid_args)
  File "/opt/conda/lib/python3.10/site-packages/dora/grid.py", line 265, in run_grid
    shepherd.commit()
  File "/opt/conda/lib/python3.10/site-packages/dora/shep.py", line 242, in commit
    self._submit(job_array)
  File "/opt/conda/lib/python3.10/site-packages/dora/shep.py", line 359, in _submit
    executor = self._get_submitit_executor(name, submitit_folder, slurm_config)
  File "/opt/conda/lib/python3.10/site-packages/dora/shep.py", line 265, in _get_submitit_executor
    executor = submitit.SlurmExecutor(
  File "/opt/conda/lib/python3.10/site-packages/submitit/slurm/slurm.py", line 249, in __init__
    raise RuntimeError('Could not detect "srun", are you indeed on a slurm cluster?')
RuntimeError: Could not detect "srun", are you indeed on a slurm cluster?`

Is there a way to run musicGen training by using Dora without setting up  slurm cluster ?

**Comment by adefossez** [comment]
You can have a look at this to run manually the jobs without Slurm:
https://github.com/facebookresearch/dora#multi-node-training-without-slurm

You won't be able to use the `dora grid` command use, although running the grid with `dora grid  GRID_NAME --dry_run --init` will allow you to use the signature with the `-f` flag in the `dora run` commands, e.g.
```
torchrun [...] -m dora run -f SIG
```

Or for single machine training you can bypass `torchrun` entirely and just use the `-d` flag.

**Comment by Frei-2** [comment]
I tried to run the command: `dora run solver=xxx, [other configurations]`, and placed configurations in the place of `[other configurations]`. It could work.

Hope it can help you.
