### ISSUE TITLE
Failing to train a pretrained model

### ISSUE THREAD

**Issue by piyuch** [facebookresearch/audiocraft#343]
I am using the following command to train an existing model:

`dora run solver=musicgen/musicgen_base_32khz model/lm/model_scale=medium continue_from=//pretrained/facebook/musicgen-medium conditioner=text2music`

But i come across the following error:

`omegaconf.errors.MissingMandatoryValue: Missing mandatory value: datasource.evaluate`

**stacktrace:**
```
Traceback (most recent call last):
  File "/opt/conda/bin/dora", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/dora/__main__.py", line 170, in main
    args.action(args, main)
  File "/opt/conda/lib/python3.10/site-packages/dora/run.py", line 51, in run_action
    xp = main.get_xp(args.argv)
  File "/opt/conda/lib/python3.10/site-packages/dora/hydra.py", line 190, in get_xp
    delta += self._get_delta(base, cfg)
  File "/opt/conda/lib/python3.10/site-packages/dora/hydra.py", line 297, in _get_delta
    for diff in _compare_config(init, other):
  File "/opt/conda/lib/python3.10/site-packages/dora/hydra.py", line 75, in _compare_config
    yield from _compare_config(ref_value, other_value, path)
  File "/opt/conda/lib/python3.10/site-packages/dora/hydra.py", line 67, in _compare_config
    ref_value = ref[key]
  File "/opt/conda/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/opt/conda/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/opt/conda/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/opt/conda/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/opt/conda/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/opt/conda/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 451, in _get_impl
    return self._resolve_with_default(
  File "/opt/conda/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 96, in _resolve_with_default
    raise MissingMandatoryValue("Missing mandatory value: $FULL_KEY")
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: datasource.evaluate
    full_key: datasource.evaluate
    object_type=dict
```

I am kind of lost, not sure what do I have to change. Any suggestion will be very helpful.

**Comment by escfrya** [comment]
You should also specify `dset=audio/your_dataset` param. Follow this [link](https://github.com/facebookresearch/audiocraft/blob/main/docs/DATASETS.md) to prepare your dataset.

**Comment by Frei-2** [comment]
@piyuch @escfrya 
I use the example dataset provided in `egs/example` and specify `dset=audio/example` param in the fine-tuning command, but still encounter a lot of errors. And the details of errors are listed [here](https://github.com/facebookresearch/audiocraft/issues/447#issuecomment-2582994865). Have you already solve this problem or have some other tips about this issue?
