### ISSUE TITLE
I don't know what error this is?

### ISSUE THREAD

**Issue by lexuwaifu** [facebookresearch/audiocraft#350]
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.10.11 (you have 3.10.6)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Traceback (most recent call last):
  File "D:\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\AI\Music AI\audiocraft\demos\musicgen_app.py", line 26, in <module>
    from audiocraft.data.audio_utils import convert_audio
  File "D:\AI\Music AI\audiocraft\audiocraft\__init__.py", line 24, in <module>
    from . import data, modules, models
  File "D:\AI\Music AI\audiocraft\audiocraft\data\__init__.py", line 10, in <module>
    from . import audio, audio_dataset, info_audio_dataset, music_dataset, sound_dataset
  File "D:\AI\Music AI\audiocraft\audiocraft\data\info_audio_dataset.py", line 19, in <module>
    from ..modules.conditioners import SegmentWithAttributes, ConditioningAttributes
  File "D:\AI\Music AI\audiocraft\audiocraft\modules\conditioners.py", line 22, in <module>
    from transformers import RobertaTokenizer, T5EncoderModel, T5Tokenizer  # type: ignore
  File "D:\Python\lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "D:\Python\lib\site-packages\transformers\dependency_versions_check.py", line 57, in <module>
    require_version_core(deps[pkg])
  File "D:\Python\lib\site-packages\transformers\utils\versions.py", line 117, in require_version_core
    return require_version(requirement, hint)
  File "D:\Python\lib\site-packages\transformers\utils\versions.py", line 111, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "D:\Python\lib\site-packages\transformers\utils\versions.py", line 44, in _compare_versions
    raise ImportError(
ImportError: accelerate>=0.20.3 is required for a normal functioning of this module, but found accelerate==0.18.0.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main

**Comment by lamHoussam** [comment]
Try creating a python virtual environment in your directory :
```powerhell
python -m venv env
```
And then activate your environment 
```powershell
.\env\Scripts\activate
```
after that try downloading torch this way:
```powershell
.\env\scripts\pip install torch==2.0.1+cu118 torchvision torchaudio
```
You can then install audiocraft.
Here is the documentatio non virtual environments:
https://docs.python.org/3/library/venv.html
