### ISSUE TITLE
Quality problems with fine-tuning the musicgen model

### ISSUE THREAD

**Issue by MajaSoure** [facebookresearch/audiocraft#447]
I would like to perform finetuning on a small musicgen model. I have a dataset consisting of different short sounds. Actually, it's not big. But I successfully trained on the melodies of one instrument, where the dataset size was extremely small, only 3 hours, and I got interesting results. However, with sounds everything is different. In 80% of cases or even more often, I encounter the fact that after the main attack sound I have a crackling sound in the generated audio track.

I've tried various ways to optimize training, but so far nothing obvious has helped, such as reducing the learning rate or dropout. Also, my logs look very suspicious from the very beginning of the training:
`Train Summary | Epoch 1 | lr=1.00E+00 | grad_norm=INF | grad_scale=45645.824 | ce=0.962 | ppl=2.650 | duration=2472.758`

It's also interesting that when I enter a word with a small letter and a word with a capital letter in the prompt, I get different results. In this case, everything depends on the word. In one case, the result is as expected, but in the other there is a complete bunch of random sounds, as if the model had not been trained. In fact, I'd be very interested to know more about how merging text tags that are packaged in json format for each sample works. I'm new to learning your model. Thanks in advance for your answer and help!

**Comment by yocontra** [comment]
These parameters might be useful to look at within the musicgen codebase, if you want to understand how it goes from json -> text:

```
dataset.train.merge_text_p
dataset.train.drop_desc_p
dataset.train.drop_other_p
conditioners.description.t5.word_dropout
```

Check out this project for a working example on fine tuning: https://github.com/sakemin/cog-musicgen-fine-tuner

**Comment by Frei-2** [comment]
@MajaSoure Hello, can I ask how you make the finetuning command run? According to the document in `audiocraft/docs/MUSICGEN.md`, I changed the model size to small, used the example dataset provided in this project and finnally used the following command:
```bash
dora run solver=musicgen/musicgen_base_32khz model/lm/model_scale=small continue_from=../cache_dir/musicgen-small conditioner=text2music dset=egs/example
```
but the results was that there were a lot of errors. 

**error 1:**
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like facebook/encodec_32khz is not the path to a directory containing a file named config.json. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
**my solution:**
I downloaded the encodec_32khz model from [facebook/encodec_32khz](https://huggingface.co/facebook/encodec_32khz/tree/main) and put it under `//reference/encodec_32khz`, accordingly I changed the `compression_model_checkpoint` value to `//reference/encodec_32khz` in the config file `musicgen_base_32khz.yaml`. However, when I ran the command again, a new error came as follows.

**error 2:**
Error executing job with overrides: ['solver=musicgen/musicgen_base_32khz', 'model/lm/model_scale=small', 'continue_from=../cache_dir/musicgen-small', 'conditioner=text2music', 'dset=audio/example']
Traceback (most recent call last):
  File "/home/yiminc/projects/audiocraft/audiocraft/train.py", line 139, in main
    solver = get_solver(cfg)
  File "/home/yiminc/projects/audiocraft/audiocraft/train.py", line 48, in get_solver
    solver = solvers.get_solver(cfg)
  File "/home/yiminc/projects/audiocraft/audiocraft/solvers/builders.py", line 62, in get_solver
    return klass(cfg)  # type: ignore
  File "/home/yiminc/projects/audiocraft/audiocraft/solvers/musicgen.py", line 39, in __init__
    super().__init__(cfg)
  File "/home/yiminc/projects/audiocraft/audiocraft/solvers/base.py", line 79, in __init__
    self.build_model()
  File "/home/yiminc/projects/audiocraft/audiocraft/solvers/musicgen.py", line 117, in build_model
    self.compression_model = CompressionSolver.wrapped_model_from_checkpoint(
  File "/home/yiminc/projects/audiocraft/audiocraft/solvers/compression.py", line 315, in wrapped_model_from_checkpoint
    compression_model = CompressionSolver.model_from_checkpoint(checkpoint_path, device)
  File "/home/yiminc/projects/audiocraft/audiocraft/solvers/compression.py", line 288, in model_from_checkpoint
    assert _checkpoint_path is not None, f"Could not resolve compression model checkpoint path: {checkpoint_path}"
AssertionError: Could not resolve compression model checkpoint path: //reference/encodec_32khz
**my solution:**
It seemed that the path to encodec_32khz was wrong, so I concretely specified it as `//reference/encodec_32khz/model.safetensors` where `model.safetensors` is the model weights I downloaded from [facebook/encodec_32khz](https://huggingface.co/facebook/encodec_32khz/tree/main). However, the other error came as follows:
Error executing job with overrides: ['solver=musicgen/musicgen_base_32khz', 'model/lm/model_scale=small', 'continue_from=../cache_dir/musicgen-small', 'conditioner=text2music', 'dset=audio/example']
Traceback (most recent call last):
  File "/home/yiminc/projects/audiocraft/audiocraft/train.py", line 139, in main
    solver = get_solver(cfg)
  File "/home/yiminc/projects/audiocraft/audiocraft/train.py", line 48, in get_solver
    solver = solvers.get_solver(cfg)
  File "/home/yiminc/projects/audiocraft/audiocraft/solvers/builders.py", line 62, in get_solver
    return klass(cfg)  # type: ignore
  File "/home/yiminc/projects/audiocraft/audiocraft/solvers/musicgen.py", line 39, in __init__
    super().__init__(cfg)
  File "/home/yiminc/projects/audiocraft/audiocraft/solvers/base.py", line 79, in __init__
    self.build_model()
  File "/home/yiminc/projects/audiocraft/audiocraft/solvers/musicgen.py", line 117, in build_model
    self.compression_model = CompressionSolver.wrapped_model_from_checkpoint(
  File "/home/yiminc/projects/audiocraft/audiocraft/solvers/compression.py", line 315, in wrapped_model_from_checkpoint
    compression_model = CompressionSolver.model_from_checkpoint(checkpoint_path, device)
  File "/home/yiminc/projects/audiocraft/audiocraft/solvers/compression.py", line 289, in model_from_checkpoint
    state = checkpoint.load_checkpoint(_checkpoint_path)
  File "/home/yiminc/projects/audiocraft/audiocraft/utils/checkpoint.py", line 93, in load_checkpoint
    state = torch.load(checkpoint_path, 'cpu')
  File "/home/yiminc/miniconda3/envs/musicgen/lib/python3.9/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/yiminc/miniconda3/envs/musicgen/lib/python3.9/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow
