### ISSUE TITLE
Wont start

### ISSUE THREAD

**Issue by Jaulustus** [facebookresearch/audiocraft#46]
Error code is this after a new install:
`C:\MusicGen\audiocraft>python app.py
Traceback (most recent call last):
  File "C:\MusicGen\audiocraft\app.py", line 11, in <module>
    from audiocraft.models import MusicGen
  File "C:\MusicGen\audiocraft\audiocraft\__init__.py", line 8, in <module>
    from . import data, modules, models
  File "C:\MusicGen\audiocraft\audiocraft\models\__init__.py", line 8, in <module>
    from .musicgen import MusicGen
  File "C:\MusicGen\audiocraft\audiocraft\models\musicgen.py", line 17, in <module>
    from .encodec import CompressionModel
  File "C:\MusicGen\audiocraft\audiocraft\models\encodec.py", line 14, in <module>
    from .. import quantization as qt
  File "C:\MusicGen\audiocraft\audiocraft\quantization\__init__.py", line 8, in <module>
    from .vq import ResidualVectorQuantizer
  File "C:\MusicGen\audiocraft\audiocraft\quantization\vq.py", line 13, in <module>
    from .core_vq import ResidualVectorQuantization
  File "C:\MusicGen\audiocraft\audiocraft\quantization\core_vq.py", line 10, in <module>
    import flashy
  File "C:\Users\Jaulustus-Desktop\AppData\Local\Programs\Python\Python310\lib\site-packages\flashy\__init__.py", line 13, in <module>
    from .logging import ResultLogger, LogProgressBar, bold, setup_logging
  File "C:\Users\Jaulustus-Desktop\AppData\Local\Programs\Python\Python310\lib\site-packages\flashy\logging.py", line 19, in <module>
    from flashy.loggers.base import ExperimentLogger
  File "C:\Users\Jaulustus-Desktop\AppData\Local\Programs\Python\Python310\lib\site-packages\flashy\loggers\__init__.py", line 8, in <module>
    from .tensorboard import TensorboardLogger
  File "C:\Users\Jaulustus-Desktop\AppData\Local\Programs\Python\Python310\lib\site-packages\flashy\loggers\tensorboard.py", line 16, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "C:\Users\Jaulustus-Desktop\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\tensorboard\__init__.py", line 7, in <module>
    raise ImportError("TensorBoard logging requires TensorBoard version 1.15 or above")
ImportError: TensorBoard logging requires TensorBoard version 1.15 or above`

**Comment by FurkanGozukara** [comment]
here full installation tutorial have you seen it? : https://youtu.be/v-YpvPkhdO4

**Comment by Jaulustus** [comment]
thy
