### ISSUE TITLE
Here are some issues when "python -m pip install -U audiocraft"

### ISSUE THREAD

**Issue by tzhou8** [facebookresearch/audiocraft#499]
Collecting scipy>=1.2.0 (from librosa->audiocraft==1.4.0a1)
  Using cached http://nexus.sii.shaipower.online/repository/pypi/packages/scipy/1.5.4/scipy-1.5.4-cp39-cp39-manylinux1_x86_64.whl (25.8 MB)
  Using cached http://nexus.sii.shaipower.online/repository/pypi/packages/scipy/1.5.3/scipy-1.5.3.tar.gz (25.2 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      Looking in indexes: http://nexus.sii.shaipower.online/repository/pypi/simple/
      Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
      Collecting wheel
        Using cached http://nexus.sii.shaipower.online/repository/pypi/packages/wheel/0.44.0/wheel-0.44.0-py3-none-any.whl (67 kB)
      Collecting setuptools
        Using cached http://nexus.sii.shaipower.online/repository/pypi/packages/setuptools/75.2.0/setuptools-75.2.0-py3-none-any.whl (1.2 MB)
      Collecting Cython>=0.29.18
        Using cached http://nexus.sii.shaipower.online/repository/pypi/packages/cython/3.0.11/Cython-3.0.11-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
      Collecting numpy==1.17.3
        Using cached http://nexus.sii.shaipower.online/repository/pypi/packages/numpy/1.17.3/numpy-1.17.3.zip (6.4 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting pybind11>=2.4.3
        Using cached http://nexus.sii.shaipower.online/repository/pypi/packages/pybind11/2.13.6/pybind11-2.13.6-py3-none-any.whl (243 kB)
      Building wheels for collected packages: numpy
        Building wheel for numpy (setup.py): started
        Building wheel for numpy (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [15 lines of output]
            Running from numpy source directory.
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/tmp/pip-install-j7z9p3rl/numpy_a66b363d881c46c0a5c6c8c7d5569fbd/setup.py", line 443, in <module>
                setup_package()
              File "/tmp/pip-install-j7z9p3rl/numpy_a66b363d881c46c0a5c6c8c7d5569fbd/setup.py", line 422, in setup_package
                from numpy.distutils.core import setup
              File "/tmp/pip-install-j7z9p3rl/numpy_a66b363d881c46c0a5c6c8c7d5569fbd/numpy/distutils/core.py", line 26, in <module>
                from numpy.distutils.command import config, config_compiler, \
              File "/tmp/pip-install-j7z9p3rl/numpy_a66b363d881c46c0a5c6c8c7d5569fbd/numpy/distutils/command/config.py", line 20, in <module>
                from numpy.distutils.mingw32ccompiler import generate_manifest
              File "/tmp/pip-install-j7z9p3rl/numpy_a66b363d881c46c0a5c6c8c7d5569fbd/numpy/distutils/mingw32ccompiler.py", line 34, in <module>
                from distutils.msvccompiler import get_build_version as get_build_msvc_version
            ModuleNotFoundError: No module named 'distutils.msvccompiler'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
        Running setup.py clean for numpy
        error: subprocess-exited-with-error
      
        × python setup.py clean did not run successfully.
        │ exit code: 1
        ╰─> [10 lines of output]
            Running from numpy source directory.
      
            `setup.py clean` is not supported, use one of the following instead:
      
              - `git clean -xdf` (cleans all files)
              - `git clean -Xdf` (cleans all versioned files, doesn't touch
                                  files that aren't checked into the git repo)
      
            Add `--force` to your command to use it anyway if you must (unsupported).
      
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for numpy
      Failed to build numpy
      ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (numpy)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by Apple-jun** [comment]
the same issue

**Comment by zjcqn** [comment]
the same issue

**Comment by zjcqn** [comment]
> the same issue

I have finish this problem by manually installing the package in the requirements.txt file and adjust the version number if encountering errors.

**Comment by tzhou8** [comment]
> > the same issue
> 
> I have finish this problem by manually installing the package in the requirements.txt file and adjust the version number if encountering errors.

pld provide your all packages requirments and your env, I'm installing on my mac, thx in advance.

**Comment by simonrouard** [comment]
Hi, we fixed the environment requirements, could you check that it works now?

**Comment by ndrw1221** [comment]
Hi, I checked and it works fine now. Thank you!
