### ISSUE TITLE
ModuleNotFoundError: No module named 'soundfile'

### ISSUE THREAD

**Issue by mettetsystems** [facebookresearch/audiocraft#52]
The Application will not start. I received this output: 

C:\Users\{ }\MusicGen\audiocraft>python app.py
Traceback (most recent call last):
  File "C:\Users\{ }\MusicGen\audiocraft\app.py", line 12, in <module>
    from audiocraft.models import MusicGen
  File "C:\Users\{ }\MusicGen\audiocraft\audiocraft\__init__.py", line 8, in <module>
    from . import data, modules, models
  File "C:\Users\{ }\MusicGen\audiocraft\audiocraft\data\__init__.py", line 8, in <module>
    from . import audio, audio_dataset
  File "C:\Users\{ }\MusicGen\audiocraft\audiocraft\data\audio.py", line 18, in <module>
    import soundfile
ModuleNotFoundError: No module named 'soundfile'

Same Error running the application in a virtual environment and the host environment.

**Comment by FurkanGozukara** [comment]
looks like installation error

i would directly install into drive not into c users

i have a step by step workflow here : https://youtu.be/v-YpvPkhdO4

**Comment by chris911024** [comment]
The error message you received indicates that the module 'soundfile' is not installed in your Python environment. The 'soundfile' module is likely a dependency of your application, and it needs to be installed for your application to work properly.

To resolve this issue, you can follow these steps:

1. Make sure you have the correct version of Python installed. Check that the version of Python you are using matches the requirements of your application.

2. Activate your virtual environment if you are using one. Run the appropriate command based on your operating system to activate the virtual environment. For example, on Windows, you can use the command:
   ```
   venv\Scripts\activate
   ```

3. Install the 'soundfile' module in your Python environment. Open a command prompt or terminal, and use the following command:
   ```
   pip install soundfile
   ```

   This command will download and install the 'soundfile' module from the Python Package Index (PyPI).

4. After the installation is complete, try running your application again:
   ```
   python app.py
   ```

   The 'soundfile' module should now be found, and your application should start without the previous error.

If you're still encountering issues, ensure that all the necessary dependencies for your application are installed correctly. You may need to check the documentation or requirements file for your application to determine the complete list of dependencies and install them accordingly.

**Comment by rsxdalv** [comment]
You might have installed https://pypi.org/project/musicgen/ which is completely unrelated except by name. Sounds like a separate problem, did you run pip install audiocraft?

**Comment by Daydricoldsmith** [comment]
I too am having this issue, I've also installed and uninstalled soundfile multiple times to no avail. It's really got me puzzled. Since i can clearly see the module in the site-packages folder, but it still doesn't detect that it's there.

Also when I reinstalled audiocraft and ran ```pip install -e . ``` it shows this:
```Requirement already satisfied: soundfile>=0.10.2 in c:\users\daydr\miniconda3\lib\site-packages (from librosa->audiocraft==0.0.2a1) (0.12.1)```

 I'm at a loss. ¯|-(ツ)-|¯

**Comment by chris911024** [comment]
cool... update can  solve  the issue

**Comment by ChrisLau23** [comment]
> cool... update can solve the issue
 you mean update `soundfile` module, right?

**Comment by ChrisLau23** [comment]
i first install this module in conda environment , it does not work.
but when i use commend `pip install soundfile`. it is successful and the code could run
